### ISSUE TITLE
msp not working

### ISSUE THREAD

**Issue by fverdoja** [jsamr/mtgaup#1]
Hi,
I have tried to use your script but it didn't work. The problem I think is that it defaults to use the .msp file for updating. In the past I have tried to use the .msp as well but in never worked for me. The .msi always did. I think then maybe having an argument to force the program to use the .msi could help.
If you can't I think I can help you implement it.
Thanks.

Here's the error I got:
```
$ MTGA_WINE_PREFIX="$HOME/Games/magic-the-gathering-arena" MTGA_WINE_BINARY="$HOME/.local/share/lutris/runners/wine/tkg-unity-4.1-x86_64/bin/wine" mtgaup
Defaulting to patch binary, if available.
Found patch binary https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1805.734606/MTGAPatch_0.1.1805.734606.msp
Download of /home/USER/Games/mtgaup/MTGAPatch_0.1.1805.734606.msp finished.
(node:17055) UnhandledPromiseRejectionWarning: Error: Command failed: /home/USER/.local/share/lutris/runners/wine/tkg-unity-4.1-x86_64/bin/wine msiexec /p "/home/USER/Games/mtgaup/MTGAPatch_0.1.1805.734606.msp"
000b:fixme:winediag:start_process Wine Staging 4.1 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0012:fixme:reg:GetEnabledXStateFeatures 
0012:fixme:wer:WerSetFlags (2) stub!
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
0009:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12)
(node:17055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fverdoja** [comment]
I'm stupid. The option is already implemented. My bad sorry.

Tried using the `-i` argument and it worked like a charm. Thank you for the nice software!

**Comment by jsamr** [comment]
@fverdoja you're very welcome :-)
