### ISSUE TITLE
Wine client version mismatch

### ISSUE THREAD

**Issue by severinkaderli** [jsamr/mtgaup#3]
When trying to use `mtgaup` I get an wine error about a version mismatch. I played the game earlier today and it was working and wanted to update.

Here's the terminal output:
```
mtgaup                                                                                                                                                                                                 
Defaulting to patch binary, if available.
Found patch binary https://mtgarena.downloads.wizards.com/Live/Windows32/versions/1810.735881/MTGAPatch_0.1.1810.735881.msp
Download of /home/severin/dev/projects/tale-doc/MTGAPatch_0.1.1810.735881.msp finished.
(node:3822028) UnhandledPromiseRejectionWarning: Error: Command failed: /home/severin/.local/share/lutris/runners/wine/tkg-unity-4.5-x86_64/bin/wine msiexec /p "/home/severin/dev/projects/tale-doc/MTGAPatch_0.1.1810.735881.msp"
wine client error:0: version mismatch 577/590.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
0009:err:process:start_wineboot failed to start wineboot, err 1359
wine client error:0: version mismatch 577/590.
Your wineserver binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
0009:fixme:winediag:start_process Wine Staging 4.5 is a testing version containing experimental patches.
0009:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0009:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:658:12)
(node:3822028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3822028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and here are my environment variables:
```
mtgaup --env-info                                                                                                                                                                                      
ENVIRONMENT VARIABLES
  MTGA_WINE_PREFIX is set to "/home/severin/games/magic-the-gathering-arena"
  MTGA_WINE_BINARY is set to "/home/severin/.local/share/lutris/runners/wine/tkg-unity-4.5-x86_64/bin/wine"
```

**Comment by jsamr** [comment]
@severinkaderli Can you assert a wine process on the same prefix is not running?

**Comment by severinkaderli** [comment]
@jsamr There is no other wine processes running. That's why the error is so strange.
```
ps -aux | grep "wine"                                                                                                                                                                                  
severin  4149523  0.0  0.0   6156  2172 pts/1    S+   22:01   0:00 grep wine
```

**Comment by jsamr** [comment]
@severinkaderli Can you launch the game on Lutris without getting this error?

Otherwise, I would bet on a Lutris issue:

- https://github.com/lutris/lutris/issues/903
- https://github.com/lutris/lutris/issues/1100

**Comment by severinkaderli** [comment]
@jsamr It was indeed an error with Lutris as well. Strangely I was able to play the game before. But I got it working again by just using my system wine for the game.

**Comment by jsamr** [comment]
@severinkaderli I'm glad it worked out!
